Module vector_mod

TYPE ODTATT
  REAL VOT
  REAL COST
  REAL TIME
  REAL DISTANCE
ENDTYPE ODTATT

TYPE ODTMEMBER
  TYPE(ODTATT), POINTER:: P(:)
  INTEGER Psize
ENDTYPE ODTMEMBER

TYPE(ODTMEMBER),ALLOCATABLE:: ODTATT_Array(:,:,:) 
!INTEGER NumOriginZone, NumSuperZone, NumIntervals

CONTAINS



SUBROUTINE ODTATTAllocate(O,D,T,NumVOTGs)
 INTEGER::O,D,T,NumVOTGs
! Allocate(ODTATT_Array(NumOriginZone,NumSuperZone,NumIntervals), stat=error)
 Allocate(ODTATT_Array(O,D,T)%P(NumVOTGs))
 
END SUBROUTINE

SUBROUTINE ODTATTInsert(O,D,T,it,VALUE1,VALUE2,VALUE3,VALUE4)

INTEGER O,D,T,it
REAL VALUE1,VALUE2,VALUE3,VALUE4

ODTATT_Array(O,D,T)%P(it)%VOT=VALUE1
ODTATT_Array(O,D,T)%P(it)%COST=VALUE2
ODTATT_Array(O,D,T)%P(it)%TIME=VALUE3
ODTATT_Array(O,D,T)%P(it)%DISTANCE=VALUE4

END SUBROUTINE

END MODULE